"""Insert sub-cluster labels from terminal output into database."""
import psycopg2
from data_pipeline.config.settings import get_config

# Sub-cluster labels from terminal output
SUB_LABELS = [
    ((0, 12), "Depressive Behaviours"),
    ((2, 29), "Music and Gait"),
    ((2, 19), "Parkinson's Symptoms"),
    ((2, 18), "Neuropsychiatric Syndromes"),
    ((2, 26), "PD Apathy Scales"),
    ((2, 23), "Exercise and Parkinson's"),
    ((3, 32), "Parkinson's Disease"),
    ((2, 22), "PD Artistic Style"),
    ((0, 1), "Apathy and Compulsivity"),
    ((2, 15), "Apathy and Depression"),
    ((2, 21), "Ischaemic Stroke Apathy"),
    ((2, 28), "PD Non-Motor Symptoms"),
    ((2, 20), "Cognitive Control Parkinson"),
    ((0, 5), "Neural Reward Mechanisms"),
    ((2, 17), "Frontostriatal Circuits"),
    ((27, 37), "Instrumental Action"),
    ((5, 48), "Aggression and Terrorism"),
    ((0, 11), "Brain-Gut Serotonin Axis"),
    ((6, 57), "Value Representation"),
    ((0, 10), "Apathy in Dementia"),
    ((6, 51), "Decision Making"),
    ((7, 66), "Striatal Reward Signaling"),
    ((2, 24), "Parkinson's Depression Treatment"),
    ((7, 65), "Raphe Serotonin Neurons"),
    ((0, 2), "Dopamine Reward Learning"),
    ((0, 4), "Medial Prefrontal Cortex"),
    ((2, 16), "Dopamine Deficiency Effects"),
    ((8, 70), "Neurocircuitry of Aversive"),
    ((8, 72), "Visual Hallucinations"),
    ((8, 68), "Decision Making Models"),
    ((7, 64), "5-HT Neurotransmission"),
    ((7, 61), "5HT2A Receptors"),
    ((2, 31), "Parkinson's Disease Pathophysiology"),
    ((7, 63), "Social Reward Circuits"),
    ((9, 75), "Locus Coeruleus Degeneration"),
    ((12, 78), "Value-Based Decision"),
    ((0, 8), "Work Motivation Theory"),
    ((9, 76), "Noradrenaline Modulation"),
    ((12, 77), "Dopamine Reward Hypothesis"),
    ((12, 87), "Pupil Size Predicts"),
    ((0, 13), "Parkinson's Disease Research"),
    ((12, 81), "Event Probability Coding"),
    ((3, 33), "Lewy Body Prodromal Symptoms"),
    ((11, 95), "Social Attention Mechanisms"),
    ((12, 84), "Time Integration Mechanism"),
    ((12, 79), "Compulsivity Neurocognition"),
    ((13, 104), "Habit Formation Theories"),
    ((14, 111), "Neurofeedback Mechanisms"),
    ((14, 113), "Neuroimaging Database"),
    ((6, 60), "Neural Feedback Processing"),
    ((6, 50), "Anterior Cingulate Cortex"),
    ((6, 52), "Belief Updates"),
    ((5, 49), "Reinforcement Learning Deficits"),
    ((16, 116), "Working Memory Models"),
    ((6, 56), "Psychophysiology"),
    ((17, 122), "Autonomic Response"),
    ((17, 118), "Network Biomarkers in Psychosis"),
    ((17, 121), "Brain Network Dynamics"),
    ((17, 123), "Brain Network Disruption"),
    ((2, 30), "Brain Parcellation"),
    ((12, 89), "Frontal Lobe Organization"),
    ((17, 119), "Social Exclusion fMRI"),
    ((18, 124), "Essential Tremor"),
    ((12, 90), "Femtocell Scheduling"),
    ((2, 14), "Carbon Monoxide Poisoning"),
    ((12, 82), "Pallidal Stimulation Effects"),
    ((0, 9), "Motor Control Models"),
    ((12, 86), "Dopamine Reward System"),
    ((19, 125), "Anterior Cingulate Cortex"),
    ((20, 127), "Decision Making Neurophysiology"),
    ((17, 117), "Hippocampal Compensation"),
    ((12, 85), "Eye Field Function"),
    ((21, 133), "Trust Formation in Interactions"),
    ((9, 74), "Neurovascular Signaling"),
    ((22, 134), "Dopamine Learning Mechanisms"),
    ((12, 83), "Cognitive Flexibility"),
    ((2, 25), "Alzheimer's Apathy Link"),
    ((11, 93), "Human Olfactory System"),
    ((0, 7), "Action Control Deficits"),
    ((0, 3), "Impulse Control Disorders"),
    ((17, 120), "Deep Learning Methods"),
    ((23, 137), "DBS Gender Disparities"),
    ((9, 73), "GBA Parkinson Disease"),
    ((2, 27), "Parkinson's Disease"),
    ((0, 0), "Neuromelanin Imaging"),
    ((7, 62), "Serotonin Modulation"),
    ((14, 114), "Value Learning Model"),
    ((6, 55), "Orbitofrontal Cortex Activity"),
    ((0, 6), "Heart Rate Variability"),
    ((19, 126), "Face Perception Efficiency"),
    ((13, 106), "Operant Conditioning"),
    ((28, 145), "Reinforcement Learning"),
    ((21, 129), "Cognitive Deficits"),
    ((6, 54), "Neural Reward Systems"),
    ((13, 100), "Neurocircuitry Analysis"),
    ((13, 99), "Alcohol Neuropathology"),
    ((14, 110), "Reward-Based Motor Learning"),
    ((13, 102), "Obsessive-Compulsive Disorder"),
    ((24, 138), "Motor Dysfunction Pathophysiology"),
    ((13, 98), "Moral Psychology"),
    ((22, 136), "Experience Shapes VIP Cells"),
    ((13, 96), "Reinforcement Learning Anhedonia"),
    ((25, 141), "Orbitofrontal Cortex Function"),
    ((6, 59), "Emotional Processing"),
    ((13, 108), "Striatal Learning Mechanisms"),
    ((6, 53), "Primate Stereotaxy"),
    ((25, 140), "Higher-Order Learning"),
    ((26, 143), "Structured Sparse Models"),
    ((14, 115), "Reinforcement Learning"),
    ((27, 44), "Striatal Activity Changes"),
    ((13, 97), "Devaluation Effects"),
    ((12, 88), "Anterior Cingulate"),
    ((8, 67), "Hyperbolic Discounting"),
    ((12, 92), "Subthreshold Voltage"),
    ((6, 58), "Orbitofrontal Control"),
    ((27, 45), "Arrestin Receptor Complex"),
    ((27, 43), "Voluntary Movement Initiation"),
    ((27, 46), "Interdisciplinary Learning"),
    ((27, 38), "Goal-Directed Avoidance"),
    ((28, 147), "Neural Autopilot"),
    ((13, 107), "Loss Aversion Decision"),
    ((13, 109), "Functional Near-Infrared Spectroscopy"),
    ((27, 41), "Basal Ganglia Coding"),
    ((14, 112), "Financial Decision Making"),
    ((29, 151), "Motor Control Models"),
    ((13, 103), "Habitual Motor Control"),
    ((27, 40), "Cognitive Neuroscience"),
    ((30, 153), "Anorexia Nervosa Pathophysiology"),
    ((12, 91), "Formal Theory of Creativity"),
    ((8, 69), "Conflict Control Networks"),
    ((8, 71), "Posterior Parietal Cortex"),
    ((31, 155), "Attentional Foci"),
    ((20, 128), "Neural Network Learning"),
    ((12, 80), "Network Complexity Measures"),
    ((32, 157), "Synaptic Plasticity"),
    ((22, 135), "Neural Value Coding"),
    ((33, 158), "Bayesian Behavioral Control"),
    ((25, 139), "Pavlovian Conditioning"),
    ((27, 39), "Perseverative Behaviour"),
    ((28, 144), "Emotion Processing"),
    ((34, 161), "Neurosymbolic Planning"),
    ((35, 163), "Memory and Metacognition"),
    ((26, 142), "Time-Varying Connectivity"),
    ((33, 160), "Internal Models"),
    ((36, 165), "Hippocampal Neural Activity"),
    ((13, 101), "Motor Sequence Execution"),
    ((36, 164), "Category Learning"),
    ((27, 35), "Motor Skill Learning"),
    ((21, 131), "Language Development Disorders"),
    ((33, 159), "Game Tree Algorithms"),
    ((13, 105), "Object Recognition"),
    ((28, 146), "Striatal Learning Systems"),
    ((27, 36), "Copyright Page"),
    ((27, 42), "Pavlovian Conditioning"),
    ((21, 130), "Brain Network Activation"),
    ((11, 94), "Successor Representations"),
    ((34, 162), "AI and Justice Alignment"),
    ((29, 149), "Corticospinal Neuron Function"),
    ((21, 132), "Data Visualization Tools"),
    ((27, 34), "Caudate Lesions"),
    ((32, 156), "Balance Mechanisms in Young Adults"),
    ((30, 152), "Neural Efficiency Anorexia"),
    ((27, 47), "Timberlake Theories"),
    ((36, 167), "Neuroscience Simulation"),
    ((29, 150), "Cerebellar Function"),
    ((37, 168), "Auditory Coding"),
    ((37, 169), "Auditory Perception"),
    ((36, 166), "Grid Cell Mechanisms"),
    ((4, 170), "Belief Updating"),
    ((28, 148), "Reinforcement Learning Options"),
    ((30, 154), "Extinction Learning"),
    ((4, 171), "Optimism and Health"),
    ((15, 172), "NADPH Oxidase"),
    ((10, 185), "Atomic Tunneling"),
    ((1, 177), "Nonlinear Energy Harvesting"),
    ((1, 183), "Piezoelectric Energy Harvesting"),
    ((1, 175), "Nonlinear Energy Harvesting"),
    ((1, 181), "Softening-Hardening Oscillator"),
    ((1, 182), "Energy Harvesting Analysis"),
    ((1, 184), "Chaos Control Methods"),
    ((1, 179), "Bird-Inspired Energy Harvesting"),
    ((1, 174), "Optomechanical Energy"),
    ((1, 178), "Bistable Energy Harvesters"),
    ((1, 176), "Smart Tires"),
    ((1, 173), "Energy Harvesting"),
    ((1, 180), "Energy Harvesting Techniques"),
]

def main():
    cfg = get_config()
    conn = psycopg2.connect(cfg.export.database_url)
    
    try:
        run_id = 33
        print(f"Inserting {len(SUB_LABELS)} sub-cluster labels for run {run_id}...")
        
        with conn.cursor() as cur:
            for (cid, sid), label in SUB_LABELS:
                cur.execute(
                    """
                    INSERT INTO sub_clusters (run_id, cluster_id, sub_cluster_id, title)
                    VALUES (%s, %s, %s, %s)
                    ON CONFLICT (run_id, cluster_id, sub_cluster_id) DO UPDATE SET title = EXCLUDED.title
                    """,
                    (run_id, cid, sid, label),
                )
        
        conn.commit()
        print(f"✓ Successfully inserted {len(SUB_LABELS)} sub-cluster labels!")
        
    finally:
        conn.close()

if __name__ == "__main__":
    main()





